---
- name: 'setup : create traefik directory'
  become: true
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: docker
    mode: 0550
  with_items:
    - '{{ traefik_dir }}'

- name: 'setup : create traefik configuration'
  become: true
  copy:
    dest: '{{ traefik_dir }}/traefik.yml'
    owner: root
    group: docker
    mode: 0550
    content: '{{ traefik_static_config | to_nice_yaml }}'
  notify:
    - restart traefik container

- name: 'setup : create traefik network'
  become: true
  docker_network:
    name: '{{ traefik_network_name }}'
    ipam_config:
      - subnet: '{{ traefik_network_ipam_subnet }}'
        gateway: '{{ traefik_network_ipam_gateway }}'
        iprange: '{{ traefik_network_ipam_iprange }}'
  vars:
    ansible_python_interpreter: "/usr/bin/env python3-docker"

- name: 'setup : start traefik service'
  community.docker.docker_swarm_service:
    name: '{{ traefik_container_name }}'
    image: '{{ traefik_image }}'
    restart_config:
      condition: any
    mounts: '{{ traefik_mounts + traefik_add_mounts }}'
    labels: '{{ traefik_labels }}'
    command:
      - '--configFile=/etc/traefik/traefik.yml'
    networks:
      - name: '{{ traefik_network_name }}'