---
- name: 'setup : create traefik directory'
  become: true
  file:
    path: '{{ traefik_dir }}'
    state: directory
    owner: root
    group: docker
    mode: 0550

- name: 'setup : create traefik configuration'
  become: true
  copy:
    dest: '{{ traefik_dir }}/traefik.yml'
    owner: root
    group: docker
    mode: 0550
    content: '{{ traefik_static_config | to_nice_yaml }}'
  notify:
    - restart traefik container

- name: "setup : build traefik docker-compose"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ traefik_dir }}/docker-compose.yml"

- name: 'setup : deploy traefik stack from a compose file'
  docker_stack:
    state: present
    name: "{{ traefik_stack_name }}"
    compose:
      - "{{ traefik_dir }}/docker-compose.yml"