---
- name: restart traefik container
  docker_stack:
    state: absent
    name: "{{ traefik_stack_name }}"
  notify:
    - start traefik container

- name: start traefik container
  docker_stack:
    state: present
    name: "{{ traefik_stack_name }}"
    compose:
      - "{{ traefik_dir }}/docker-compose.yml"
  register: result
  until: result.rc == 0
  retries: 3
  delay: 2